### ISSUE TITLE
[Request] Can i have the latest version source code of BlackJack?

### ISSUE THREAD

**Issue by vanduck241** [Perotins/Blackjack#1]
Hello there, it seems like the current source code version is 1.5.3 and the latest on spigot is 1.6.2. The reason why i want the source code is because i want to edit some in it to make it more compatible with Vietnamese players (im making a vietnamese minecraft server) and of course it totally a private plugin, all credits will be kept. Thank you. Have a nice day

I'm a Vietnamese student and my english still not good at all, sorry about that.

**Comment by maximus-f** [comment]
yea I will, sorry that this is really late but I will in the next few days.

**Comment by MelonHell** [comment]
Please update the source code

**Comment by maximus-f** [comment]
Done
