### ISSUE TITLE
Items can be taken our of the comtinue screen

### ISSUE THREAD

**Issue by CloudeLecaw** [Perotins/Blackjack#3]
When u finsihed a blackjack game you come to the screen where you can decide if ou want to continue or not (continue screen)
There u can take off all items our of the screen

![image](https://user-images.githubusercontent.com/12080017/112756927-ad248080-8fe7-11eb-87db-be91ac72f421.png)

Blackjack_1.6.3
Server: Paper
![image](https://user-images.githubusercontent.com/12080017/112756967-d04f3000-8fe7-11eb-8907-1f424fc7ef8f.png)

**Comment by maximus-f** [comment]
thanks for pointing this out. will look into it.

**Comment by CloudeLecaw** [comment]
i really hope u find a solution would be nice to see a blackjack comeback with 1.19.1

**Comment by CloudeLecaw** [comment]
looks like it is caused because the items are renamed?
Here a video with the differences with renamed items and original config.
https://streamable.com/zmbbm9

**Comment by maximus-f** [comment]
Fixed
