### ISSUE TITLE
Items can be taken out of end GUI

### ISSUE THREAD

**Issue by JJBirdgender** [Perotins/Blackjack#4]
Players can take items out of the end GUI, server is 1.18.2 papermc, everything was working fine until I configured the names and things in config.yml, I restarted the server and now the players can take items out of the gui once they finish playing. maybe add an option to disable the play again gui at the end, instead players must run the command again to play again? I hope you can fix the problem as this plugin is great! I think perhaps this is a bug or not support for 1.18.2 however it was working fine before config change.

**Comment by CloudeLecaw** [comment]
See here i also run into this problem and see a reason for it
https://github.com/Perotins/Blackjack/issues/3

**Comment by maximus-f** [comment]
Fix is now on spigot!
