### ISSUE TITLE
Info on login tells me there is an update to download, even if i allready updated to 1.6.5?

### ISSUE THREAD

**Issue by CloudeLecaw** [Perotins/Blackjack#7]
Info on login tells me there is an update to download, even if i allready updated to 1.6.5?
![Snag_1e25f3e](https://user-images.githubusercontent.com/12080017/230698324-9c7d8924-0e0a-4ef9-9047-270d89e6de19.png)

Is this a bug or because its new?

**Comment by maximus-f** [comment]
Hm, not sure. It is not a new thing, only you see that message as an admin. It depends on the version of the plugin.yml, see if the plugin.yml is 1.6.5

**Comment by CloudeLecaw** [comment]
you see this only as addming correct and no its not plugin yml in this case

i was checking it before i reported
```
name: Blackjack
main: me.perotin.blackjack.Blackjack
version: 1.6.5
author: Perotin
depends: [Vault]
api-version: 1.13
```

Might be it was spigot aggain blaming devs for releasing a new version sometimes 1-2 days before it works correct with their update checker.

message is not shown anymore
